### ISSUE TITLE
syncano-client s.get doesnt send data

### ISSUE THREAD

**Issue by aexol** [Syncano/syncano-node#151]
```
s.get('socket/endpoint',{a:1,b:2})
```
Doesnt add data to request just userkey.

Versions: 0.8.0, canary

**Comment by mkucharz** [comment]
@aexol can you check now?

**Comment by adamwardecki** [comment]
Noticed a couple of things:

1. Initialize the Client lib without the user key:
`const s = new SyncanoClient(INSTANCE)`

then when doing requests, the first query param gets an `&`, like so:
`https://late-mountain-7516.syncano.space/hello/hello/?&_method=GET`

2. Some of the unit tests are false positive because there's no `axiosMock.reset()` in the beforeEach.
